server:
  port: 8080

spring:
  application:
    name: accounts

  profiles:
    active: "prod"

  config:
#    import: "optional:configserver:http://localhost:8071/" (if connection was not possible by whatever reason then it will user the default config avaialble in this file)
#    import: "configserver:http://localhost:8071/"
    import: "configserver:http://configserver:8071/"

  datasource:
    # using host.docker.interna because wanted to use local postgres data base
#    url: jdbc:postgresql://localhost:5433/accountsdb?TimeZone=Asia/Kolkata
#    url: jdbc:postgresql://localhost:5432/postgres?TimeZone=Asia/Kolkata
    url: jdbc:postgresql://host.docker.internal:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: Asia/Kolkata

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true
  endpoint:
    health:
      show-details: always
    shutdown:
#      enabled: true
      access: unrestricted

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


# this info will be available in the Eureka Dashboard when you will click on the link under Status tab
info:
  app:
    name: "accounts"
    description: "Eazy Bank Accounts Application"
    version: "1.0.0"