server:
  port: 8090

spring:
  application:
    name: loans

  profiles:
    active: "prod"

  config:
    import: "configserver:http://configserver:8071/"
#    import: "configserver:http://localhost:8071/"

  datasource:
    # using host.docker.interna because wanted to use local postgres data base
#    url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://host.docker.internal:5432/postgres
#    url: jdbc:postgresql://localhost:5434/loansdb?TimeZone=Asia/Kolkata
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      idle-timeout: 30000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
      jdbc:
        time_zone: Asia/Kolkata

#  rabbitmq:
#    host: "localhost"
#    port: 5672
#    username: "guest"
#    password: "guest"

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/


# this info will be available in the Eureka Dashboard when you will click on the link under Status tab
info:
  app:
    name: "loans"
    description: "Eazy Bank Loans Application"
    version: "1.0.0"